### ISSUE TITLE
Kategorie

### ISSUE THREAD

**Issue by HannaSchaefer** [ralfhe/FoReWeb#11]
Wenn ich nach Eis suche, findet er nur Gerichte die Eis heißen. Wenn ich stattdessen Magnum eingebe, gibt es alle Sorten. Könnte man diese auch unter der Eis-Suche anzeigen lassen?

**Comment by ralfhe** [comment]
Hatten wir drüber gesprochen. Ist sehr schwer und nur möglich, wenn man Meta-Informationen zu Magnunm hat und diese bei der Suche mit einbezieht. Da Magnum und andere Marken jedoch vollständig über APIs bezogen werden, hat man hier auch keine Möglichkeit auf die Suche einzuwirken.
