### ISSUE TITLE
Religion

### ISSUE THREAD

**Issue by SilviaKo** [ralfhe/FoReWeb#4]
I see a ethical problem with "religion", as you might be jewish but still eat milk and meat at the same time. I'd rather go for a system just ticking "I don't eat meat" or else. People are always picky when it comes to religion.

**Comment by ralfhe** [comment]
Talked about this issue with Hanna a couple of minutes ago and came to the same conclusion. We will dismiss religion and rather have a differentiation upon tase and preferences.

**Comment by ralfhe** [comment]
Removed.
