### ISSUE TITLE
Snacks are not shown

### ISSUE THREAD

**Issue by HannaSchaefer** [ralfhe/FoReWeb#6]
You can enter Snacks in the Diary but not see them later

**Comment by ralfhe** [comment]
@HannaSchaefer @SilviaKo How should we handle this in general? At the moment I have divided everything up into the following categories: breakfast, lunch, dinner, snack, drink or other but only breakfast, lunch and dinner is displayed. I think we need to decided on the following questions:

1. Do we need this categories in general for the diary?
2. If yes, do we need all of them?
3. If yes, how shall we handle beverages?

**Comment by HannaSchaefer** [comment]
I think it does not hurt us to offer all of them. Maybe we can simplify it to meal, snack and beverage, but it is still the same effort for the user. Also for the recommendations, it makes it easier to extend the system if we have categories like breakfast, so we can later recommend those separately.

**Comment by SilviaKo** [comment]
I agree with Hanna, however I wouldn't simplify. I'd go for the calssics breakfast, lunch, dinner, snack, this is what people are familiar with. I'd handle beverages not as a separete group, as e.g. for breakfast, people drink coffee. It might be confusing for them to have an extra category of beverages. We should however include a discription: please add the beverages to the accompanied meals, beverages you drink during the day without accompanied meals are to be added to "Snacks".

**Comment by ralfhe** [comment]
Classification for now limited to breakfast, lunch, dinner and snack. Snacks are displayed now.
