### ISSUE TITLE
Only those dates with data clickable

### ISSUE THREAD

**Issue by HannaSchaefer** [ralfhe/FoReWeb#9]
I would always make the dates clickable and then just show and empty diary

**Comment by ralfhe** [comment]
Why? What would be the advantage of it? At the moment it is implemented like that, that you can choose any date you want to enter a new entry and from the earliest entry on until today the dates can be selected even if not all dates are filled with data. E.g. New entry for 1.10.15, no entries from 2.10.15 until now. Then all dates from 1.10. until now would be clickable.

**Comment by HannaSchaefer** [comment]
I did not know it was the complete range, I thought only the single days with entries. Maybe that is a good compromise. I just as a user am confused when I cannot click something without knowing the reason.
